### DISCUSSION TITLE
`cndi` E200 - cndi-config must contain exactly one leader node

### DISCUSSION THREAD

**Discussion by johnstonmatt** [polyseam/cndi#463] [Error Message Discussion]
### description

The `cndi` CLI exits with error code `200` when you call `cndi overwrite` (aka. `cndi ow`) with a `cndi-config` file which either designates multiple leaders, or designates none. CNDI is used to create clusters of one or many nodes, and there always must be one node with the role of `"leader"`. Note how in the config below there is exactly one node with the property `"role"` set to `"leader"`.

```yaml
cndi_version: v1
project_name: my-cndi-project
infrastructure:
  cndi:
    cert_manager:
      email: jane.doe@example.com
    nodes:
      - name: x-node
        kind: ec2
        role: leader
        instance_type: t3.2xlarge
        volume_size: 128
      - name: y-node
        kind: ec2
        role: controller
        volume_size: 128
      - name: z-node
        kind: ec2
        volume_size: 128
```

### resolution tips

In order to resolve this issue, select a node to be leader of the cluster, then call `cndi ow` again.
