### DISCUSSION TITLE
`cndi` E203 - `cndi-config` contains unknown `infrastructure.terraform` keys

### DISCUSSION THREAD

**Discussion by johnstonmatt** [polyseam/cndi#506] [Error Message Discussion]
### description

The `cndi` CLI exits with error code `203` when you call `cndi overwrite` (aka. `cndi ow`) with a `cndi-config` file which includes an entry in the `infrastructure.terraform` object which is not a known Terraform block type.

Recognized block types are: 
```js
[
  "terraform",
  "provider",
  "variable",
  "output",
  "locals",
  "resource",
  "data",
  "module"
]
```

Here is an example of an invalid configuration:

```yaml
cndi_version: v1
project_name: my-cndi-broken
infrastructure:
  terraform:
    foo: # foo is not in the list of recognized block types
      bar: baz
```

### resolution tips

In order to resolve this issue, remove the invalid block key from `cndi-config.infrastructure.terraform`. If you believe the key should be recognized, please let us know in this thread.
