### DISCUSSION TITLE
`cndi` E702 - failure to persist a Kubernetes Secret with stringData from `cndi-config`

### DISCUSSION THREAD

**Discussion by johnstonmatt** [polyseam/cndi#549] [Error Message Discussion]
### description

The `cndi` CLI exits with error code `702` when a Kubernetes Secret resource is created without any data or stringData

### resolution tips
incorrect:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: bad-secret-example
```
---
correct:
```bash
# .env
MY_VAR='bar'
```
```yaml
# correct:
apiVersion: v1
kind: Secret
metadata:
  name: good-secret-example
stringData:
  foo: '$.cndi.secrets.seal(MY_VAR)'
```

Passing a `$.cndi.secrets(MY_VAR)` alongside defining `MY_VAR` in your environment, will result in that value being inserted into a new SealedSecret, and shared with your cluster in a secure way.

If you are intending to declare a secret without a value, please drop us a line in this thread
