### DISCUSSION TITLE
`cndi` E908 - `cndi-config` file contains a `infrastructure.cndi.open_ports` block which is not an array

### DISCUSSION THREAD

**Discussion by johnstonmatt** [polyseam/cndi#576] [Error Message Discussion]
### description

The `cndi` CLI exits with error code `908` when it is passed a `cndi-config` file contains a `infrastructure.cndi.open_ports` block which is not an array.

### resolution tips

Please try running `cndi overwrite` again after you have updated the `open_ports` to be an array of port specifications, or removed the block completely.

A correctly formed `open_ports` looks like this:

```yaml
infrastructure:
  cndi:
    open_ports:
      - name: tcp-bolt
        number: 7687
        service: neo4j
        namespace: neo4j
```
