### DISCUSSION TITLE
`cndi` E909 - `cndi-config` contains an `infrastructure.cndi.open_ports` entry which contains a `service`, but not a `namespace`

### DISCUSSION THREAD

**Discussion by johnstonmatt** [polyseam/cndi#578] [Error Message Discussion]
### description

The `cndi` CLI exits with error code `909` when it is passed a `cndi-config` file contains a `infrastructure.cndi.open_ports` block which contains an element that defines a `service` but not a `namespace` in which to find it

### resolution tips

If you are exposing a `service` with your open_ports entry, you must also specify a `namespace`. If you are opening a port which does not expose a service, please declare neither.

A correctly formed `open_ports` which opens a service looks like this:

```yaml
infrastructure:
  cndi:
    open_ports:
      - name: tcp-bolt
        number: 7687
        service: neo4j
        namespace: neo4j
```

A correctly formed `open_ports` entry which does not open a service looks like this:

```yaml
infrastructure:
  cndi:
    open_ports:
      - name: kubeapi
        number: 16443
```
