### DISCUSSION TITLE
`cndi` E910 - `cndi-config` contains an `infrastructure.cndi.open_ports` entry which contains a `namespace`, but not a `service`

### DISCUSSION THREAD

**Discussion by johnstonmatt** [polyseam/cndi#579] [Error Message Discussion]
### description

The `cndi` CLI exits with error code `910` when it is passed a `cndi-config` file contains a `infrastructure.cndi.open_ports` block which contains an element that defines a `namespace` but not a `service` to expose within.

### resolution tips

If you are exposing a `service` with your open_ports entry, you must also specify a `service` and a `namespace`. If you are opening a port which does not expose a service, please declare neither.

A correctly formed `open_ports` which opens a service looks like this:

```yaml
infrastructure:
  cndi:
    open_ports:
      - name: tcp-bolt
        number: 7687
        service: neo4j
        namespace: neo4j
```

A correctly formed `open_ports` entry which does not open a service looks like this:

```yaml
infrastructure:
  cndi:
    open_ports:
      - name: kubeapi
        number: 16443
```
