### DISCUSSION TITLE
`cndi` E810 - failed to generate AKS terraform resources because `cndi_config.yaml` node names were invalid

### DISCUSSION THREAD

**Discussion by johnstonmatt** [polyseam/cndi#707] [Error Message Discussion]
### description

The `cndi` CLI exits with error code `810` when your node names in your cndi_config.yaml file are incompatible with AKS Node Pool Specs.

### resolution tips

Please update the `name` property in each `cndi_config.yaml[infrastructure][cndi][nodes]` entry to an alphanumeric value with 12 or fewer characters.

Eg:

```yaml
cndi_version: v2
project_name: example-aks
provider: azure
distribution: aks
infrastructure:
  cndi:
    cert_manager:
      email: matt.johnston@polyseam.io
    nodes:
      - name: smallname # update this line
        disk_size: 100
      - name: smallnameb # and this line!
        disk_size: 100
```
