### DISCUSSION TITLE
`cndi` E1203 - @cndi/use-template failed to find a built-in "validator"

### DISCUSSION THREAD

**Discussion by johnstonmatt** [polyseam/cndi#862] [Error Message Discussion]
### description

The `cndi` CLI exits with error code `1203` when it recieves a `prompt.validators` entry which CNDI does not recognize. For example @cndi/use-template does not have a builtin validator for `isFoo`, so we should expect the CLI to throw when it finds a prompt like the following:

```yaml
  - name: maybe_foo
    default: bar
    message: >-
      Please provide a foo!
    type: Input
    validators:
      - isFoo
```

### resolution tips

If you aren't the author of the Template you're using, please call `cndi upgrade` in case that the validator list is up to date.

If you are the Template author please check the supported validators list here and make a pull request if necessary:
https://github.com/polyseam/cndi/blob/main/src/use-template/util/validation.ts
