### ISSUE TITLE
[Enhancement]: Ensure CNDI Subsystems are Self-Evident

### ISSUE THREAD

**Issue by johnstonmatt** [polyseam/cndi#772]
### Version

cndi v2.4.4
kubeseal v0.26.0
terraform v1.5.5

### Please provide a summary of the enhancement you are proposing:

We provision a bunch of applications and configuration for the user in the `infrastructure.cndi` block of a `cndi_config.yaml` file. These configuration objects are designed to be terse and minimal, but we think it could be an improvement to showing how they can be disabled and updated for understandability.

eg.:
```yaml
cndi_version: v2
project_name: mj-rad-mar14-cluster
provider: aws
distribution: microk8s
infrastructure:
  cndi:
    open_ports:
      - name: kubeapi
        number: 16443
        enabled: false
    cert_manager:
      email: matt.johnston@polyseam.io
``` 

### Please provide the motivation or use case for this enhancement:

CNDI is simplifying configuration for the user, and adding more verbose config entries can make it easier for users to understand what is being simplified, how to update configuration, and generally not be confused by the "magic"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
