### ISSUE TITLE
[Bug]: Prompt Identifier Evaluated before condition

### ISSUE THREAD

**Issue by johnstonmatt** [polyseam/cndi#918]
### What happened?

CNDI is supposed to evaluate the `body.condition` of a block before trying to evaluate the identifier. When this goes wrong the following statement can fail to resolve:
```yaml
        external_dns: 
          $cndi.get_block(https:/raw.githubusercontent.com/polyseam/cndi/main/blocks/external-dns/config/{{ $cndi.get_prompt_response(dns_provider) }}.yaml):
            condition:
              - "{{ $cndi.get_prompt_response(enable_external_dns) }}"
              - ==
              - true
```

the above should have tolerated a missing `dns_provider` if the condition evaluated to false

### Version

cndi v2.12.0
kubeseal v0.26.0
terraform v1.5.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
